version: '3'
services:

  api:
    build: .
    container_name: api
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017